### ISSUE TITLE
znalezione błędy

### ISSUE THREAD

**Issue by zybex86** [dao0dao/DaylyTimeline#1]
## Do poprawy:

* Rezerwując kort jako nowy gracz mogę wpisać co chcę w
nazwisko - pojawi się scroll przesuwający pole żebym mógł przeczytać całe nazwisko
* Po dodaniu nowego gracza do listy graczy, nie pojawia się nowo do dany gracz na liście, tylko
trzeba odświeżyć
* Brak sortowania graczy - jakieś raczej powinno być.
* Guzik dodaj powinien pojawiać się jak zjedziemy niżej scrollem, a znikać jak widać guzik
`Dodaj Rezerwacje`. Zmieniłbym też napis `latającego guzika DODAJ` na `dodaj rezerwację` albo
oba poprostu na `REZERWUJ`
* Dodałem rezerwacje która zaczyna się przed początkiem następnej a kończy po następnej...
* Na Firefox nie pojawia się możliwość wybrania godziny, tylko mogę wpisać z ręki, natomiast
na chrome jest możliwość wyboru
* Na chrome jest czas 24 godzinny a na firefox 12 godzinny.
* ID nieunikatowe jest na liście graczy
* Konsola wariuje jak dodam gracza
```
ERROR TypeError: Cannot read property 'length' of null
    at template (main.5b28fa5091308601a284.js:1)
    at Os (main.5b28fa5091308601a284.js:1)
    at Cs (main.5b28fa5091308601a284.js:1)
    at Xs (main.5b28fa5091308601a284.js:1)
    at main.5b28fa5091308601a284.js:1
    at Cs (main.5b28fa5091308601a284.js:1)
    at main.5b28fa5091308601a284.js:1
    at Cs (main.5b28fa5091308601a284.js:1)
    at Xs (main.5b28fa5091308601a284.js:1)
    at main.5b28fa5091308601a284.js:1
mr @ main.5b28fa5091308601a284.js:1
handleError @ main.5b28fa5091308601a284.js:1
(anonymous) @ main.5b28fa5091308601a284.js:1
invoke @ polyfills.9bf4dad123bd95dda86e.js:1
run @ polyfills.9bf4dad123bd95dda86e.js:1
runOutsideAngular @ main.5b28fa5091308601a284.js:1
tick @ main.5b28fa5091308601a284.js:1
(anonymous) @ main.5b28fa5091308601a284.js:1
invoke @ polyfills.9bf4dad123bd95dda86e.js:1
onInvoke @ main.5b28fa5091308601a284.js:1
invoke @ polyfills.9bf4dad123bd95dda86e.js:1
run @ polyfills.9bf4dad123bd95dda86e.js:1
run @ main.5b28fa5091308601a284.js:1
next @ main.5b28fa5091308601a284.js:1
r @ main.5b28fa5091308601a284.js:1
__tryOrUnsub @ main.5b28fa5091308601a284.js:1
next @ main.5b28fa5091308601a284.js:1
_next @ main.5b28fa5091308601a284.js:1
next @ main.5b28fa5091308601a284.js:1
next @ main.5b28fa5091308601a284.js:1
emit @ main.5b28fa5091308601a284.js:1
nu @ main.5b28fa5091308601a284.js:1
iu @ main.5b28fa5091308601a284.js:1
onInvokeTask @ main.5b28fa5091308601a284.js:1
invokeTask @ polyfills.9bf4dad123bd95dda86e.js:1
runTask @ polyfills.9bf4dad123bd95dda86e.js:1
invokeTask @ polyfills.9bf4dad123bd95dda86e.js:1
_ @ polyfills.9bf4dad123bd95dda86e.js:1
k @ polyfills.9bf4dad123bd95dda86e.js:1
load (async)
O @ polyfills.9bf4dad123bd95dda86e.js:1
scheduleTask @ polyfills.9bf4dad123bd95dda86e.js:1
onScheduleTask @ polyfills.9bf4dad123bd95dda86e.js:1
scheduleTask @ polyfills.9bf4dad123bd95dda86e.js:1
scheduleTask @ polyfills.9bf4dad123bd95dda86e.js:1
scheduleEventTask @ polyfills.9bf4dad123bd95dda86e.js:1
(anonymous) @ polyfills.9bf4dad123bd95dda86e.js:1
(anonymous) @ main.5b28fa5091308601a284.js:1
_trySubscribe @ main.5b28fa5091308601a284.js:1
subscribe @ main.5b28fa5091308601a284.js:1
E @ main.5b28fa5091308601a284.js:1
_innerSub @ main.5b28fa5091308601a284.js:1
_tryNext @ main.5b28fa5091308601a284.js:1
_next @ main.5b28fa5091308601a284.js:1
next @ main.5b28fa5091308601a284.js:1
(anonymous) @ main.5b28fa5091308601a284.js:1
_trySubscribe @ main.5b28fa5091308601a284.js:1
subscribe @ main.5b28fa5091308601a284.js:1
call @ main.5b28fa5091308601a284.js:1
subscribe @ main.5b28fa5091308601a284.js:1
call @ main.5b28fa5091308601a284.js:1
subscribe @ main.5b28fa5091308601a284.js:1
call @ main.5b28fa5091308601a284.js:1
subscribe @ main.5b28fa5091308601a284.js:1
submit @ main.5b28fa5091308601a284.js:1
(anonymous) @ main.5b28fa5091308601a284.js:1
Oo @ main.5b28fa5091308601a284.js:1
s @ main.5b28fa5091308601a284.js:1
r @ main.5b28fa5091308601a284.js:1
__tryOrUnsub @ main.5b28fa5091308601a284.js:1
next @ main.5b28fa5091308601a284.js:1
_next @ main.5b28fa5091308601a284.js:1
next @ main.5b28fa5091308601a284.js:1
next @ main.5b28fa5091308601a284.js:1
emit @ main.5b28fa5091308601a284.js:1
onSubmit @ main.5b28fa5091308601a284.js:1
(anonymous) @ main.5b28fa5091308601a284.js:1
Oo @ main.5b28fa5091308601a284.js:1
s @ main.5b28fa5091308601a284.js:1
(anonymous) @ main.5b28fa5091308601a284.js:1
invokeTask @ polyfills.9bf4dad123bd95dda86e.js:1
onInvokeTask @ main.5b28fa5091308601a284.js:1
invokeTask @ polyfills.9bf4dad123bd95dda86e.js:1
runTask @ polyfills.9bf4dad123bd95dda86e.js:1
invokeTask @ polyfills.9bf4dad123bd95dda86e.js:1
_ @ polyfills.9bf4dad123bd95dda86e.js:1
k @ polyfills.9bf4dad123bd95dda86e.js:1
Show 46 more frames
main.5b28fa5091308601a284.js:1 ERROR TypeError: Cannot read property 'length' of null
    at template (main.5b28fa5091308601a284.js:1)
    at Os (main.5b28fa5091308601a284.js:1)
    at Cs (main.5b28fa5091308601a284.js:1)
    at Xs (main.5b28fa5091308601a284.js:1)
    at main.5b28fa5091308601a284.js:1
    at Cs (main.5b28fa5091308601a284.js:1)
    at main.5b28fa5091308601a284.js:1
    at Cs (main.5b28fa5091308601a284.js:1)
    at Xs (main.5b28fa5091308601a284.js:1)
    at main.5b28fa5091308601a284.js:1
```

**Comment by dao0dao** [comment]
- Wprowadziłem ograniczenie długości imiona (15 znaków) oraz nazwiska (30 znaków).
- Brak nowego gracza po jego dodaniu był spowodowany błędem `ERROR TypeError: Cannot read property 'length' of null`. Błąd 
 naprawiłem.
- Wprowadziłem blokady dodawania rezerwacji rozpoczynającej się prze początkiem następnej a kończącej się po następnej.
- Zgodnie z dokumentacją MDN: `Chrome and Opera: 12 or 24-hour format depending on operating system locale`, `Firefox: It also uses a 12- or 24-hour format for inputting times, based on system locale`. Format czasu jest zależny od lokalnych ustawień systemu.
- Zmienione ID na unikatowe na liście graczy.

Jestem w trakcie tworzenia modułu filtrującego graczy.

**Comment by zybex86** [comment]
1. dostaje jeszcze taki błąd jak dodaję rezerwację drugi raz
`ERROR TypeError: t is null`

Błąd pojawia się kiedy chcę dodać nową rezerwację po pomyślnym dodaniu poprzedniej. - odznaczone są wtedy opcje `Nowy Gracz` oraz `lista graczy` a po wybraniu drugiej opcji nie widać graczy. 

1. Nadal ciągle widoczny guzik dodaj, nawet jak jestem na górze strony i widze guzik DODAJ REZERWACJĘ - jeżeli tak ma zostać to ignoruj ten komentarz :)

**Comment by dao0dao** [comment]
- Naprawiłem błąd `TypeError: t is null`
- Lista już się pojawia.

Odnośnie przyciska dodaj rezerwację - cały czas rozmyślam nad kilkoma koncepcjami dlatego jeszcze tam są. Zajmę się nimi po tym jak dodam przyciski filtrujące listę graczy po imieniu, nazwisku cenie.

**Comment by zybex86** [comment]
Filtr wygląda spoko. Jedynie uważam że ikony `AZ` / `ZA` są zbyteczne, ale to kwestia gustu - typowo wystarczają strzałki w filtrowaniu i te strzałki zmieniają kierunek.

Zastanawia mmnie też że jak klikne dwa razy to wszystkie pola zmieniają kierunek filtrowania... nie powinno to być osobne dla każdego pola?

**Comment by dao0dao** [comment]
Ikony AZ/ ZA zostają, mi się podobają. Teraz po przełączeniu filtru ustawiają się domyślnie na rosnący kierunek. Myślę, że temat został wyczerpany :)
